
TYPE
	MACHINE_WORKING_STATE : 
		( (*Working state of whole machine*)
		STATE_IDLE,
		STATE_TUNING,
		STATE_WORKING_MANUAL,
		STATE_WORKING_AUTOMATIC,
		STATE_ERROR,
		STATE_STOP
		);
	ZONE_WORKING_STATE : 
		( (*Working state of each zone*)
		STATE_IDLE_ZONE,
		STATE_HEATING,
		STATE_COOLING
		);
	AUTOMATIC_MODE_STATE : 
		( (*Step of automatic mode*)
		STEP_INIT,
		STEP1,
		STEP2,
		STEP3,
		STEP4,
		STEP5
		);
END_TYPE
