
TYPE
	MACHINE_WORKING_STATE : 
		( (*Stan pracy dzialania calej maszyny*)
		STATE_IDLE,
		STATE_TUNING,
		STATE_WORKING_MANUAL,
		STATE_WORKING_AUTOMATIC,
		STATE_ERROR,
		STATE_STOP
		);
	ZONE_WORKING_STATE : 
		(
		STATE_IDLE_ZONE,
		STATE_HEATING,
		STATE_COOLING
		);
END_TYPE
